import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '../components/navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'CuyAnimelist',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressContentEditableWarning={true}>
        <div>
          <Navbar />
          <div className="px-5">{children}</div>
        </div>
      </body>
    </html>
  );
}
